import request from "@/lib/request";

const BASEURL = "/api/users";

/**
 * Request body for post user: username and password
 * @param username username of the user. Must be unique.
 * @param password unencrypted password. Will be BCrypted in backend.
*/
export interface CreateUserRequest {
    username: string;
    password: string;
}

/**
 * Response body for post user: id, username, and createdAt
 * @param id unique id generated by DB.
 * @param username newly registered username.
 * @param createdAt timestamp of user creation.
 * 
*/
export interface CreateUserResponse {
    id: number;
    username: string;
    createdAt: string;
}

/**
 * Post request for user creation
 * @param data Request body
 * @returns Response body of creating new user
 * 
*/
export const createUser = (data: CreateUserRequest) =>
    request.post<CreateUserResponse>(BASEURL, data);

/**
 * Check if a username exists: use it for new user registration
 * @param username Username to be checked
 * @returns True if username exists, false otherwise
*/
export const checkUsername = (username: string) =>
    request.get<boolean>(`${BASEURL}/exists`, {params: {username: username}});

/**
 * Response body for GET /api/me: only the username, resolved server-side
 * from the authenticated principal (see TestController#getMethodName).
 * @param username the logged-in user's username.
*/
export interface CurrentUserResponse {
    username: string;
}

/**
 * Fetch the currently authenticated user (based on the jwt cookie).
 * Note: this hits /api/me, not /api/users/me — that's where the backend
 * actually exposes it (see TestController), not under the /api/users prefix.
 * @returns { username } for the logged-in user
 */
export const getCurrentUser = () => request.get<CurrentUserResponse>("/api/me");