import request from "@/lib/request";

const BASEURL = "/api/users";

/**
 * Request body for post user: username and password
 * @param username username of the user. Must be unique.
 * @param password unencrypted password. Will be BCrypted in backend.
*/
export interface CreateUserRequest {
    username: string;
    password: string;
}

/**
 * Response body for post user: id, username, and createdAt
 * @param id unique id generated by DB.
 * @param username newly registered username.
 * @param createdAt timestamp of user creation.
 * 
*/
export interface CreateUserResponse {
    id: number;
    username: string;
    createdAt: string;
}

/**
 * Post request for user creation
 * @param data Request body
 * @returns Response body of creating new user
 * 
*/
export const createUser = (data: CreateUserRequest) =>
    request.post<CreateUserResponse>(BASEURL, data);

/**
 * Check if a username exists: use it for new user registration
 * @param username Username to be checked
 * @returns True if username exists, false otherwise
*/
export const checkUsername = (username: string) =>
    request.get<boolean>(`${BASEURL}/exists`, {params: {username: username}});